Wrapping Up
-----------

This guide is intended to give you, the chart developer, a strong
understanding of how to use Helm’s template language. The guide focuses
on the technical aspects of template development.

But there are many things this guide has not covered when it comes to
the practical day-to-day development of charts. Here are some useful
pointers to other documentation that will help you as you create new
charts:

* The https://github.com/kubernetes/charts[Kubernetes Charts project] is
an indispensable source of charts. That project is also sets the
standard for best practices in chart development.
* The Kubernetes http://kubernetes.io/docs/user-guide/[User’s Guide]
provides detailed examples of the various resource kinds that you can
use, from ConfigMaps and Secrets to DaemonSets and Deployments.
* The Helm link:../charts.md[Charts Guide] explains the workflow of
using charts.
* The Helm link:../charts_hooks.md[Chart Hooks Guide] explains how to
create lifecycle hooks.
* The Helm link:../charts_tips_and_tricks.md[Charts Tips and Tricks]
article provides some useful tips for writing charts.
* The https://github.com/Masterminds/sprig[Sprig documentation]
documents more than sixty of the template functions.
* The https://godoc.org/text/template[Go template docs] explain the
template syntax in detail.
* The https://github.com/databus23/schelm[Schelm tool] is a nice helper
utility for debugging charts.

Sometimes it’s easier to ask a few questions and get answers from
experienced developers. The best place to do that is in the Kubernetes
`#Helm` Slack channel:

* https://slack.k8s.io/[Kubernetes Slack]: `#helm`

Finally, if you find errors or omissions in this document, want to
suggest some new content, or would like to contribute, visit
https://github.com/kubernetes/helm[The Helm Project].
