Kubernetes Distribution Guide
-----------------------------

This document captures information about using Helm in specific
Kubernetes environments.

We are trying to add more details to this document. Please contribute
via Pull Requests if you can.

MiniKube
~~~~~~~~

Helm is tested and known to work with
https://github.com/kubernetes/minikube[minikube]. It requires no
additional configuration.

`scripts/local-cluster` and Hyperkube
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Hyperkube configured via `scripts/local-cluster.sh` is known to work.
For raw Hyperkube you may need to do some manual configuration.

GKE
~~~

Google’s GKE hosted Kubernetes platform enables RBAC by default. You
will need to create a service account for tiller, and use the
–service-account flag when initializing the helm server.

See https://docs.helm.sh/using_helm/#role-based-access-control[Tiller
and role-based access control] for more information.

Ubuntu with `kubeadm'
~~~~~~~~~~~~~~~~~~~~~

Kubernetes bootstrapped with `kubeadm` is known to work on the following
Linux distributions:

* Ubuntu 16.04
* Fedora release 25

Some versions of Helm (v2.0.0-beta2) require you to
`export KUBECONFIG=/etc/kubernetes/admin.conf` or create a
`~/.kube/config`.

Container Linux by CoreOS
~~~~~~~~~~~~~~~~~~~~~~~~~

Helm requires that kubelet have access to a copy of the `socat` program
to proxy connections to the Tiller API. On Container Linux the Kubelet
runs inside of a
https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube[hyperkube]
container image that has socat. So, even though Container Linux doesn’t
ship `socat` the container filesystem running kubelet does have socat.
To learn more read the
https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html[Kubelet
Wrapper] docs.

Openshift
~~~~~~~~~

Helm works straightforward on OpenShift Online, OpenShift Dedicated,
OpenShift Container Platform (version >= 3.6) or OpenShift Origin
(version >= 3.6). To learn more read
https://blog.openshift.com/getting-started-helm-openshift/[this blog]
post.

Platform9
~~~~~~~~~

Helm Client and Helm Server (Tiller) are pre-installed with
https://platform9.com/managed-kubernetes/?utm_source=helm_distro_notes[Platform9
Managed Kubernetes]. Platform9 provides access to all official Helm
charts through the App Catalog UI and native Kubernetes CLI. Additional
repositories can be manually added. Further details are available in
this
https://platform9.com/support/deploying-kubernetes-apps-platform9-managed-kubernetes/?utm_source=helm_distro_notes[Platform9
App Catalog article].

DC/OS
~~~~~

Helm (both client and server) has been tested and is working on
Mesospheres DC/OS 1.11 Kubernetes platform, and requires no additional
configuration.
