Related Projects and Documentation
----------------------------------

The Helm community has produced many extra tools, plugins, and
documentation about Helm. We love to hear about these projects. If you
have anything you’d like to add to this list, please open an
https://github.com/kubernetes/helm/issues[issue] or
https://github.com/kubernetes/helm/pulls[pull request].

Article, Blogs, How-Tos, and Extra Documentation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* https://github.com/cdwv/awesome-helm[Awesome Helm] - List of awesome
Helm resources
* http://www.slideshare.net/Diacode/cicd-with-kubernetes-helm-wercker-madscalability[CI/CD
with Kubernetes, Helm & Wercker]
* http://technosophos.com/2017/03/21/creating-a-helm-plugin.html[Creating
a Helm Plugin in 3 Steps]
* http://cloudacademy.com/blog/deploying-kubernetes-applications-with-helm/[Deploying
Kubernetes Applications with Helm]
* https://medium.com/@enxebre/gitlab-consumer-driven-contracts-helm-and-kubernetes-b7235a60a1cb#.xwp1y4tgi[GitLab,
Consumer Driven Contracts, Helm and Kubernetes]
* https://gist.github.com/so0k/f927a4b60003cedd101a0911757c605a[Honestbee’s
Helm Chart Conventions]
* https://medium.com/@enxebre/releasing-backward-incompatible-changes-kubernetes-jenkins-plugin-prometheus-operator-helm-self-6263ca61a1b1#.e0c7elxhq[Releasing
backward-incompatible changes: Kubernetes, Jenkins, Prometheus Operator,
Helm and Traefik]
* https://hackernoon.com/the-missing-ci-cd-kubernetes-component-helm-package-manager-1fe002aac680#.691sk2zhu[The
Missing CI/CD Kubernetes Component: Helm package manager]
* https://deis.com/blog/2017/workflow-chart-assembly[The Workflow
``Umbrella'' Helm Chart]
* https://daemonza.github.io/2017/02/20/using-helm-to-deploy-to-kubernetes/[Using
Helm to Deploy to Kubernetes]
* https://www.influxdata.com/packaged-kubernetes-deployments-writing-helm-chart/[Writing
a Helm Chart]
* https://github.com/muffin87/helm-tutorial[A basic walk through
Kubernetes Helm]
* https://rimusz.net/tillerless-helm/[Tillerless Helm v2]

Video, Audio, and Podcast
~~~~~~~~~~~~~~~~~~~~~~~~~

* https://www.youtube.com/watch?v=NVoln4HdZOY[CI/CD with Jenkins,
Kubernetes, and Helm]: AKA ``The Infamous Croc Hunter Video''.
* https://gcppodcast.com/post/episode-50-helm-with-michelle-noorali-and-matthew-butcher/[Helm
with Michelle Noorali and Matthew Butcher]: The official Google
CloudPlatform Podcast interviews Michelle and Matt about Helm.
* https://www.youtube.com/watch?v=zBc1goRfk3k&index=49&list=PLj6h78yzYM2PqgIGU1Qmi8nY7dqn9PCr4[KubeCon2016:
Delivering Kubernetes-Native Applications by Michelle Noorali]

Helm Plugins
~~~~~~~~~~~~

* https://github.com/app-registry/helm-plugin[App Registry] - Plugin to
manage charts via the https://github.com/app-registry/spec[App Registry
specification]
* https://github.com/databus23/helm-diff[Helm Diff] - Preview
`helm upgrade` as a coloured diff
* https://github.com/skuid/helm-value-store[Helm Value Store] - Plugin
for working with Helm deployment values
* https://github.com/technosophos/helm-plugins[Technosophos’s Helm
Plugins] - Plugins for GitHub, Keybase, and GPG
* https://github.com/imroc/helm-cos[helm-cos] - Plugin to manage
repositories on Tencent Cloud Object Storage
* https://github.com/mstrzele/helm-edit[helm-edit] - Plugin for editing
release’s values
* https://github.com/adamreese/helm-env[helm-env] - Plugin to show
current environment
* https://github.com/nouney/helm-gcs[helm-gcs] - Plugin to manage
repositories on Google Cloud Storage
* https://github.com/sagansystems/helm-github[helm-github] - Plugin to
install Helm Charts from Github repositories
* https://github.com/balboah/helm-hashtag[helm-hashtag] - Plugin for
tracking docker tag hash digests as values
* https://github.com/cststack/k8comp[helm-k8comp] - Plugin to create
Helm Charts from hiera using k8comp
* https://github.com/adamreese/helm-last[helm-last] - Plugin to show the
latest release
* https://github.com/adamreese/helm-local[helm-local] - Plugin to run
Tiller as a local daemon
* https://github.com/ContainerSolutions/helm-monitor[helm-monitor] -
Plugin to monitor a release and rollback based on
Prometheus/ElasticSearch query
* https://github.com/adamreese/helm-nuke[helm-nuke] - Plugin to destroy
all releases
* https://github.com/futuresimple/helm-secrets[helm-secrets] - Plugin to
manage and store secrets safely
* https://github.com/IBM/helm-stop[helm-stop] - Plugin for stopping a
release pods
* https://github.com/technosophos/helm-template[helm-template] -
Debug/render templates client-side
* https://github.com/adamreese/helm-tiller[helm-tiller] - Additional
commands to work with Tiller
* https://github.com/lrills/helm-unittest[helm-unittest] - Plugin for
unit testing chart locally with YAML
* https://github.com/rimusz/helm-tiller[Tillerless Helm v2] - Helm
plugin for using Tiller locally and in CI/CD pipelines

We also encourage GitHub authors to use the
https://github.com/search?q=topic%3Ahelm-plugin&type=Repositories[helm-plugin]
tag on their plugin repositories.

Additional Tools
~~~~~~~~~~~~~~~~

Tools layered on top of Helm or Tiller.

* https://github.com/appscode/swift[AppsCode Swift] - Ajax friendly Helm
Tiller Proxy using
https://github.com/grpc-ecosystem/grpc-gateway[grpc-gateway]
* https://github.com/att-comdev/armada[Armada] - Manage prefixed
releases throughout various Kubernetes namespaces, and removes completed
jobs for complex deployments. Used by the
https://github.com/openstack/openstack-helm[Openstack-Helm] team.
* https://github.com/reactiveops/autohelm[Autohelm] - Autohelm is
_another_ simple declarative spec for deploying helm charts. Written in
python and supports git urls as a source for helm charts.
* https://github.com/chartmuseum/chartmuseum[ChartMuseum] - Helm Chart
Repository with support for Amazon S3 and Google Cloud Storage
* https://github.com/appscode/chartify[Chartify] - Generate Helm charts
from existing Kubernetes resources.
* https://codefresh.io[Codefresh] - Kubernetes native CI/CD and
management platform with UI dashboards for managing Helm charts and
releases
* https://github.com/ohaiwalt/cog-helm[Cog] - Helm chart to deploy Cog
on Kubernetes
* http://plugins.drone.io/ipedrazas/drone-helm/[Drone.io Helm Plugin] -
Run Helm inside of the Drone CI/CD system
* https://github.com/luizbafilho/helm-chart-publisher[Helm Chart
Publisher] - HTTP API for publishing Helm Charts in an easy way
* https://github.com/qmfrederik/helm[Helm.NET] - A .NET client for
Tiller’s API
* https://github.com/roboll/helmfile[Helmfile] - Helmfile is a
declarative spec for deploying helm charts
* https://github.com/Praqma/helmsman[Helmsman] - Helmsman is a
helm-charts-as-code tool which enables
installing/upgrading/protecting/moving/deleting releases from version
controlled desired state files (described in a simple TOML format). +
* https://github.com/Eneco/landscaper/[Landscaper] - ``Landscaper takes
a set of Helm Chart references with values (a desired state), and
realizes this in a Kubernetes cluster.''
* https://github.com/helm/monocular[Monocular] - Web UI for Helm Chart
repositories
* https://coreos.com/blog/quay-application-registry-for-kubernetes.html[Quay
App Registry] - Open Kubernetes application registry, including a Helm
access client
* https://github.com/AcalephStorage/rudder[Rudder] - RESTful (JSON)
proxy for Tiller’s API
* https://github.com/databus23/schelm[Schelm] - Render a Helm manifest
to a directory
* https://github.com/andrewstuart/vim-kubernetes[VIM-Kubernetes] - VIM
plugin for Kubernetes and Helm

Helm Included
~~~~~~~~~~~~~

Platforms, distributions, and services that include Helm support.

* http://www.skippbox.com/cabin/[Cabin] - Mobile App for Managing
Kubernetes
* https://fabric8.io[Fabric8] - Integrated development platform for
Kubernetes
* http://jenkins-x.io/[Jenkins X] - open source automated CI/CD for
Kubernetes which uses Helm for
http://jenkins-x.io/about/features/#promotion[promoting] applications
through http://jenkins-x.io/about/features/#environments[environments
via GitOps]
* https://kubernetic.com/[Kubernetic] - Kubernetes Desktop Client
* https://qstack.com[Qstack]

Misc
~~~~

Grab bag of useful things for Chart authors and Helm users

* https://github.com/saltside/await[Await] - Docker image to ``await''
different conditions–especially useful for init containers.
http://blog.slashdeploy.com/2017/02/16/introducing-await/[More Info]
